### **Student Information**
Name: 吳花瑜

Student ID: 114065534

GitHub ID: huayu1115

Kaggle name: huayu1115

Kaggle private scoreboard snapshot: 

![pic_ranking.png](./pics/pic_ranking.png)

---

# **Instructions**

For this lab we have divided the assignments into **three phases/parts**. The `first two phases` refer to the `exercises inside the Master notebooks` of the [DM2025-Lab2-Exercise Repo](https://github.com/difersalest/DM2025-Lab2-Exercise.git). The `third phase` refers to an `internal Kaggle competition` that we are gonna run among all the Data Mining students. Together they add up to `100 points` of your grade. There are also some `bonus points` to be gained if you complete `extra exercises` in the lab **(bonus 15 pts)** and in the `Kaggle Competition report` **(bonus 5 pts)**.

**Environment recommendations to solve lab 2:**
- **Phase 1 exercises:** Need GPU for training the models explained in that part, if you don't have a GPU in your laptop it is recommended to run in Colab or Kaggle for a faster experience, although with CPU they can still be solved but with a slower execution.
- **Phase 2 exercises:** We use Gemini's API so everything can be run with only CPU without a problem.
- **Phase 3 exercises:** For the competition you will probably need GPU to train your models, so it is recommended to use Colab or Kaggle if you don't have a laptop with a dedicated GPU.
- **Optional Ollama Notebook (not graded):** You need GPU, at least 4GB of VRAM with 16 GB of RAM to run the local open-source LLM models. 

## **Phase 1 (30 pts):**

1. __Main Exercises (25 pts):__ Do the **take home exercises** from Sections: `1. Data Preparation` to `9. High-dimension Visualization: t-SNE and UMAP`, in the [DM2025-Lab2-Master-Phase_1 Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_1.ipynb). Total: `8 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 3th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**. 

## **Phase 2 (30 pts):**

1. **Main Exercises (25 pts):** Do the remaining **take home exercises** from Section: `2. Large Language Models (LLMs)` in the [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb). Total: `5 exercises required from sections 2.1, 2.2, 2.4 and 2.6`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**. 

3. **`Bonus (15 pts):`** Complete the bonus exercises in the [DM2025-Lab2-Master-Phase_2_Bonus Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Bonus.ipynb) and [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb) `where 2 exercises are counted as bonus from sections 2.3 and 2.5 in the main notebook`. Total: `7 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

## **Phase 3 (40 pts):**

1. **Kaggle Competition Participation (30 pts):** Participate in the in-class **Kaggle Competition** regarding Emotion Recognition on Twitter by clicking in this link: **[Data Mining Class Kaggle Competition](https://www.kaggle.com/t/3a2df4c6d6b4417e8bf718ed648d7554)**. The scoring will be given according to your place in the Private Leaderboard ranking: 
    - **Bottom 40%**: Get 20 pts of the 30 pts in this competition participation part.

    - **Top 41% - 100%**: Get (0.6N + 1 - x) / (0.6N) * 10 + 20 points, where N is the total number of participants, and x is your rank. (ie. If there are 100 participants and you rank 3rd your score will be (0.6 * 100 + 1 - 3) / (0.6 * 100) * 10 + 20 = 29.67% out of 30%.)   
    Submit your last submission **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**. Make sure to take a screenshot of your position at the end of the competition and store it as `pic_ranking.png` under the `pics` folder of this repository and rerun the cell **Student Information**.

2. **Competition Report (10 pts)** A report section to be filled in inside this notebook in Markdown Format, we already provided you with the template below. You need to describe your work developing the model for the competition. The report should include a section describing briefly the following elements: 
* Your preprocessing steps.
* The feature engineering steps.
* Explanation of your model.

* **`Bonus (5 pts):`**
    * You will have to describe more detail in the previous steps.
    * Mention different things you tried.
    * Mention insights you gained. 

[Markdown Guide - Basic Syntax](https://www.markdownguide.org/basic-syntax/)

**`Things to note for Phase 3:`**

* **The code used for the competition should be in this Jupyter Notebook File** `DM2025-Lab2-Homework.ipynb`.

* **Push the code used for the competition to your repository**.

* **The code should have a clear separation for the same sections of the report, preprocessing, feature engineering and model explanation. Briefly comment your code for easier understanding, we provide a template at the end of this notebook.**

* Showing the kaggle screenshot of the ranking plus the code in this notebook will ensure the validity of your participation and the report to obtain the corresponding points.

After the competition ends you will have two days more to submit the `DM2025-Lab2-Homework.ipynb` with your report in markdown format and your code. Do everything **`BEFORE the deadline (Nov. 26th, 11:59 pm, Wednesday) to obtain 100% of the available points.`**

Upload your files to your repository then submit the link to it on the corresponding NTU Cool assignment.

## **Deadlines:**

![lab2_deadlines](./pics/lab2_deadlines.png)

---

Next you will find the template report with some simple markdown syntax explanations, use it to structure your content.

You can delete the syntax suggestions after you use them.

---

***

# **Project Report**
    
**Syntax:** `#` creates the largest heading (H1).    
**Syntax:** `##` creates a secondary heading (H2).    
**Syntax:** `###` creates a tertiary heading (H3).    
**Syntax:** `---` creates a horizontal rule (a separator line).    
    
**Example Syntax for Content:**
*   **Bold text:** `**text**`
*   *Italic text*: `*text*`
*   Bullet point list:
    * Item 1
    * Item 2
    
Markdown Syntax to Add Image: `![Description of the Image](./your_local_folder/name_of_the_image.png)`     

![Example Markdown Syntax to Add Image](./pics/example_md_img.png)    

---
## 0. Kaggle leaderboard    



## 1. Model Development (10 pts Required)

**Describe briefly each section, you can add graphs/charts to support your explanations.**

### 1.1 Preprocessing Steps



[Content for Preprocessing]





### 1.2 Feature Engineering Steps
![Emotion Distribution](./pics/emotion_distribution.png)    
我們可以看到 joy 和 anger 的數量最多，若沒有做特殊處理，模型分類表現會在這兩個類別上最好    


### 1.3 Explanation of Your Model
因為資料集不大，為了提高輸出準確率，我選擇採用遷移式學習方法，利用少量的資料微調預訓練模型。    
我選擇 roberta-base

---

## 2. Bonus Section (5 pts Optional)

**Add more detail in previous sections**

### 2.1 Mention Different Things You Tried

[Content for Experiments]

### 2.2 Mention Insights You Gained

[Content for Insights]

---

**`From here on starts the code section for the competition.`**

---

# **Competition Code**

## 1. Preprocessing Steps

In [1]:
# 讀csv
import os
import pandas as pd
import json

data_identification = pd.read_csv("data\competition\data_identification.csv")
emotion = pd.read_csv("data\competition\emotion.csv")
samplesubmission = pd.read_csv("data\competition\samplesubmission.csv")

In [2]:
# 讀 json
with open(r"data\competition\final_posts.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

records = []
for item in data:
    root = item.get("root", {})
    _type = root.get("_type")
    post_info = root.get("_source", {}).get("post", {})

    record = {
        "_type": _type,
        "post_id": post_info.get("post_id"),
        "text": post_info.get("text"),
        "hashtags": post_info.get("hashtags"),
    }
    records.append(record)

df = pd.DataFrame(records)
df.head()

  _type   post_id                                               text hashtags
0  post  0x61fc95  We got the ranch, loaded our guns and sat up t...       []
1  post  0x35663e  I bet there is an army of married couples who ...       []
2  post  0xc78afe                         This could only end badly.       []
3  post  0x90089c  My sister squeezed a lime in her milk when she...       []
4  post  0xaba820         and that got my head bobbing a little bit.       []

In [3]:
train_df = pd.merge(
    emotion,
    df,
    left_on='id',      
    right_on='post_id',
    how='inner'       
).drop(columns=['post_id'])
print(len(train_df))
train_df.head()

47890

,id,emotion,_type,text,hashtags
0,0x35663e,joy,post,I bet there is an army of married couples who ...,[]
1,0xc78afe,fear,post,This could only end badly.,[]
2,0x90089c,joy,post,My sister squeezed a lime in her milk when she...,[]
3,0x2ffb63,joy,post,Thank you so much❤️,[]
4,0x989146,joy,post,Stinks because ive been in this program for a ...,[]

In [4]:
test_df = pd.merge(
    samplesubmission,
    df,
    left_on='id',      
    right_on='post_id',
    how='inner'       
).drop(columns=['post_id'])
print(len(test_df))
test_df.head()

16281

,id,emotion,_type,text,hashtags
0,0x42a94c,surprise,post,We went to bed.,[]
1,0xbc5e67,surprise,post,i used to think the fire detector going off at...,[]
2,0xdb5812,surprise,post,She sat at her Papa's recliner sofa only to mo...,[]
3,0x0e9e68,surprise,post,25 m from Canada! out for 10 years now! I'd lo...,[]
4,0xf085f1,surprise,post,I have to finally tell my therapist about my s...,[singlegirlproblems]

## 2. Feature Engineering Steps

看 train, test 的比例

In [5]:
print(data_identification['split'].value_counts())

split
train    47890
test     16281
Name: count, dtype: int64

看情緒的分布

In [6]:
print(emotion['emotion'].value_counts())

emotion
joy         23797
anger       10694
surprise     6281
sadness      3926
fear         2009
disgust      1183
Name: count, dtype: int64

看 hashtags 數量

In [7]:
non_empty_counts = train_df['hashtags'].apply(bool).value_counts()
print(non_empty_counts)
non_empty_counts = test_df['hashtags'].apply(bool).value_counts()
print(non_empty_counts)

hashtags
False    45382
True      2508
Name: count, dtype: int64
hashtags
False    15241
True      1040
Name: count, dtype: int64

_type 皆為 post

In [8]:
print(train_df['_type'].value_counts())
print(test_df['_type'].value_counts())

_type
post    47890
Name: count, dtype: int64
_type
post    16281
Name: count, dtype: int64

In [9]:
train_df.drop(columns=['_type'], inplace=True)
test_df.drop(columns=['_type'], inplace=True)

觀察 hashtags 欄位: 只有少部分資料有 hashtags

In [10]:
non_empty_counts = df['hashtags'].apply(bool).value_counts()
print(non_empty_counts)
df_with_hashtags = df[df['hashtags'].apply(bool)]
df_with_hashtags.head()

hashtags
False    60623
True      3548
Name: count, dtype: int64

,_type,post_id,text,hashtags
14,post,0xb855e1,Rap that will Cut other raper's throat. Who sa...,"[badd, wicked, bright]"
41,post,0x0a0102,Having a baby born too soon is #lifechanging 6...,"[lifechanging, sad, happy, emotionalrollercoas..."
55,post,0x745c66,@ananavarro @tcarrels most of Trump supporters...,"[sad, nevertrump]"
60,post,0xb41434,@ananavarro @tcarrels most of Trump supporters...,[nevertrump]
61,post,0x75fc2c,Tomorrow is the day I cut and dye my hair! 😳 #...,"[nervous, excited]"

## 3. Model Implementation Steps

In [11]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn import CrossEntropyLoss
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, classification_report
import numpy as np

d:\miniconda\envs\dm2025\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [12]:
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU count:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))

PyTorch version: 2.5.1
CUDA available: True
GPU count: 1
GPU name: NVIDIA GeForce RTX 2070 Super

情緒標籤編碼

In [13]:
label2id = {"joy":0, "anger":1, "surprise":2, "sadness":3, "fear":4, "disgust":5}
id2label = {v:k for k,v in label2id.items()}
train_df["label_id"] = train_df["emotion"].map(label2id)

分割訓練集與驗證集，用分層抽樣 stratified sampling，保持原本標籤的比例分布

In [14]:
train_texts, val_texts, train_labels, val_labels = train_test_split(
    train_df["text"].tolist(),
    train_df["label_id"].tolist(),
    test_size=0.2,
    random_state=42,
    stratify=train_df["label_id"]
)

test_texts = test_df["text"].tolist()

建立 roberta-base Tokenizer

In [15]:
model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

MAX_LEN = 200
def tokenize(texts):
    return tokenizer(texts, padding="max_length", truncation=True, max_length=MAX_LEN, return_tensors="pt")

建立 Dataset: tokenize 句子

In [16]:
class EmotionDataset(Dataset):
    def __init__(self, texts, tokenizer, labels=None):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            padding="max_length",
            truncation=True,
            max_length=MAX_LEN,
            return_tensors="pt"
        )
        
        item = {key: val.squeeze(0) for key, val in encoding.items()}

        # only include labels if available
        if self.labels is not None:
            item["labels"] = torch.tensor(self.labels[idx])

        return item

In [17]:
train_dataset = EmotionDataset(train_texts, tokenizer, labels=train_labels)
val_dataset = EmotionDataset(val_texts, tokenizer, labels=val_labels)
test_dataset = EmotionDataset(test_texts, tokenizer)  # labels=None

In [18]:
train_dataset[0].keys()

dict_keys(['input_ids', 'attention_mask', 'labels'])

利用 class weights 處理不平衡

In [19]:
counts = train_df["label_id"].value_counts().sort_index().tolist()  # 按 label_id 排序
weights = [sum(counts)/c for c in counts]
weights = torch.tensor(weights).float()
print(weights)

tensor([ 2.0124,  4.4782,  7.6246, 12.1982, 23.8377, 40.4818])

使用 GPU 加速

In [20]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda

使用預訓練模型

In [29]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=6
).to(device)

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

設定加權損失和訓練參數

In [ ]:
'''
class WeightedLossTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        # forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")
        
        # 定義加權 Loss
        loss_fct = CrossEntropyLoss(weight=weights)
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        
        return (loss, outputs) if return_outputs else loss

# 定義 Metrics
def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    # Macro F1 適合類別不平衡
    f1 = f1_score(p.label_ids, preds, average="macro")
    return {"f1": f1}

# 訓練參數優化
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,             
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,               # 防止過擬合
    warmup_ratio=0.1,                # 學習率預熱
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    logging_dir='./logs',
    logging_steps=100,               
)
'''

In [ ]:
loss_fn = CrossEntropyLoss(weight=weights)

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_dir='./logs',
    learning_rate=2e-5,
    load_best_model_at_end=True,
    metric_for_best_model="f1"
)

d:\miniconda\envs\dm2025\Lib\site-packages\transformers\training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Metrics

In [ ]:
def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    f1 = f1_score(p.label_ids, preds, average="macro")
    return {"f1": f1}

Trainer

In [40]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

C:\Users\NPC\AppData\Local\Temp\ipykernel_14732\2721217396.py:1: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [41]:
trainer.train()

TrainOutput(global_step=2395, training_loss=0.8166754529471189, metrics={'train_runtime': 966.7347, 'train_samples_per_second': 39.63, 'train_steps_per_second': 2.477, 'total_flos': 3937762805126400.0, 'train_loss': 0.8166754529471189, 'epoch': 1.0})

驗證集評估

In [42]:
val_output = trainer.predict(val_dataset)
preds = np.argmax(val_output.predictions, axis=1)
print("Classification Report:\n")
print(classification_report(val_labels, preds, target_names=list(label2id.keys())))

Classification Report:

              precision    recall  f1-score   support

         joy       0.80      0.84      0.82      4759
       anger       0.59      0.67      0.63      2139
    surprise       0.63      0.52      0.57      1256
     sadness       0.49      0.42      0.45       785
        fear       0.54      0.56      0.55       402
     disgust       0.30      0.04      0.07       237

    accuracy                           0.69      9578
   macro avg       0.56      0.51      0.51      9578
weighted avg       0.68      0.69      0.68      9578

In [43]:
test_output = trainer.predict(test_dataset)
predictions = np.argmax(test_output.predictions, axis=1)
pred_labels = [id2label[i] for i in predictions]

In [44]:
submission_df = pd.DataFrame({
    "id": test_df.id, 
    "emotion": pred_labels
})

# Save to CSV
submission_df.to_csv("test_predictions.csv", index=False)